name: Build ESP
on:
  push:
  pull_request:
jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: '3.x'
      - name: Install Platform IO
        run: |
          python -m pip install --upgrade pip
          pip install -U esphome
      - name: Validate ESP8266 Config
        run: esphome config peopleCounter.yaml
      - name: Build ESP8266
        run: esphome compile peopleCounter.yaml
      - name: Validate ESP32 Config
        run: esphome config peopleCounter32.yaml
      - name: Build ESP32
        run: esphome compile peopleCounter32.yaml
      
